### ISSUE TITLE
Normalize delta by window.devicePixelRatio (Chrome)

### ISSUE THREAD

**Issue by haraldreingruber** [basilfx/normalize-wheel#1]
This library looks really interesting as a replacement for my own solution, which was only tested for a couple of platforms.

Is the current implementation tested also with different devicePixelRatio?

I am asking because I had to normalize the wheelDelta on Chrome+Win10 also by window.devicePixelRatio  for systems where a different screen scaling is configured.

**Comment by basilfx** [comment]
Hi @haraldreingruber,

To be honest, I do not know. This code is just a copy-paste from [Facebook's Fixed Data Table](https://github.com/facebook/fixed-data-table), with minor changes to make it work stand-alone.

Kind regards,
Bas
